
      <div id="micrositeHeader">
		<img src="<?php print $pot;?>/images/glee_header.jpg" />
      </div>



      <div id="micrositeMenu" class="/*<?php print $node->type;?>*/">
		<div id="micrositeMenuCenter">
		<div id="navHome">
		<a href="/">Glee Casting Home</a>
		</div>
		<div id="navPhotos">
		<a href="/russell-gallery-redirect-page">Glee Casting Photo Gallery</a>
		</div>
		<div id="navVideos">
		<a href="http://video.oxygen.com/shows/glee_casting">Glee Casting Videos</a>
		</div>
		<div id="navBlogs">
		<a href="http://glee.oxygen.com/blogs/glee">Glee Casting Blogs</a>
		</div>
		<div id="navCasting">
		<a href="/glee-contestant-application">Sign up for the Glee Project</a>
		</div>
		<div id="navAudition">
		<a href="/about-glee_casting">About Glee Auditions</a>
		</div>
		<div id="navAbout">
		<a href="/about-glee_casting">About Glee</a>
		</div>
		<div id="navBoards">
		<a href="http://forums.oxygen.com/index.php?showforum=31">Chat On The Glee Casting Message Boards</a>
		</div>
		</div>
	</div>