<?php
// $Id$  promo_title_alt_copy.module August 8, 2011 Randall Goya decibel.places
// Adds links to copy Blurb and Link Text fields to image title and alt

if (!isset($thenodetype)){
if ('node' == arg(0)){
if (arg(2) != "edit") $thenodetype = str_replace('-', '_', arg(2)); // This is the node type
//if (arg(2) != "edit") $thenodetype = arg(2); // This is the node type
else if(is_numeric(arg(1))) {
  $node = node_load(arg(1));
  $thenodetype = $node->type;
}
}
}

//dsm($thenodetype);
//dsm('title_alt');

if (strpos($thenodetype, 'promo') > 0)
{
	drupal_add_js(drupal_get_path('module', 'promo_title_alt_copy') . '/promo_title_alt_copy.js', 'module');
}

/**
 * set module weight to load after crop_presets module
 * see http://drupal.org/node/110238
 */
$weight = db_result(db_query("SELECT weight FROM {system} WHERE name = 'crop_presets'"));
db_query("UPDATE {system} SET weight = %d WHERE name = 'promo_title_alt_copy'", $weight + 1);