      <div id="micrositeHeader">
		<img src="<?php print $pot;?>/images/mainHeader.jpg" />
      </div>



      <div id="micrositeMenu" class="<?php print $node->type;?>">
		<div id="micrositeMenuCenter">
		<div id="navHome">
		<a href="/">Bad Girls Club Home</a>
		</div>
		<div id="navMeet">
		<a href="/meet-the-cast-bgc">Bad Girls Club Bios</a>
		</div>		
		<div id="navPhotos">
		<a href="/bgc-photo-gallery-redirect-page">Bad Girls Club Photo Gallery</a>
		</div>
		<div id="navVideos">
		<a href="http://video.oxygen.com/shows/bad_girls_club_season_4#////shows/bad_girls_club_season_4/bad_girls_club_season_4_bonus_act_recaps/">Bad Girls Club Videos</a>
		</div>
		<div id="navBlogs">
		<a href="/blogs/bgc" >Bad Girls Club Blogs</a>
		</div>
		<div id="navExtras">
		<a href="/bad-girls-club-extras" >Bad Girls Club Extras</a>
		</div>
		<div id="navBoards">
		<a href="http://forums.oxygen.com/index.php?showforum=3">Chat On The Bad Girls Club Message Boards</a>
		</div>
		<div id="navAbout">
		<a href="/about-the-bad-girls-club">About The Bad Girls Club Show</a>
		</div>
		<div id="navShop">
		<a href="http://www.shopoholic.com/b2c/PK/ecom/ecomEnduser/items/2-S0-lV1BadGirlsCl-lV2BG.aspx" target="_blank">Bad Girls Club Shop</a>
		</div>
		<div id="navCasting">
		<a href="/bad-girls-club-casting">Bad Girls Club Casting</a>
		</div>
		</div>
	</div>