      <div id="micrositeHeader">
		<img src="<?php print $pot;?>/images/no_egg.jpg" />
      </div>



      <div id="micrositeMenu" class="<?php print $node->type;?>">
		<div id="micrositeMenuCenter">
		<div id="navHome">
		<a href="/">House of Glam Home</a>
		</div>
		<div id="navMeet">
		<a href="http://house-of-glam.oxygen.com/meet-the-cast-hog">House of Glam Bios</a>
		</div>		
		<div id="navPhotos">
		<a href="/hog-photo-gallery-redirect-page">House of Glam Photo Gallery</a>
		</div>
		<div id="navVideos">
		<a href="http://video.oxygen.com/shows/house_of_glam">House of Glam  Videos</a>
		</div>
		<div id="navBlogs">
		<a href="http://house-of-glam.oxygen.com/blogs/hog">House of Glam Blogs</a>
		</div>
		<div id="navBoards">
		<a href="http://forums.oxygen.com/index.php?showforum=27">Chat On The House of Glam  Message Boards</a>
		</div>
		<div id="navAbout">
		<a href="/about-house-of-glam">About The House of Glam </a>
		</div>
		</div>
	</div>