<?php

/**
 * Implementation of hook_strongarm().
 */
function promo_sortable_fieldsets_strongarm() {
  $export = array();
  $strongarm = new stdClass;
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'jquery_update_replace';
  $strongarm->value = TRUE;

  $export['jquery_update_replace'] = $strongarm;
  return $export;
}
