<!--<?='test' ?>-->

      <div id="micrositeHeader">
		<img src="<?php print $pot;?>/images/mainHeader.jpg" />
      </div>



      <div id="micrositeMenu" class="<?php print $node->type;?>">
		<div id="micrositeMenuCenter">
		<div id="navHome">
		<a href="/">Addicted to Beauty Home</a>
		</div>
		<div id="navMeet">
		<a href="/meet-the-cast-atb">Meet The Cast</a>
		</div>		
		<div id="navPhotos">
		<a href="/atb-gallery-redirect-page">Photo Gallery</a>
		</div>
		<div id="navBlogs">
		<a href="" style="background-position: -285px 0px;cursor:default;">Addicted to Beauty Blogs</a>
		</div>
		<div id="navVideos">
		<a href="http://o2.oxygen.com/player/?fid=1133397">Addicted to Beauty Videos</a>
		</div>
		<div id="navWebSeries">
		<a href="/addicted-to-gary">Addicted to Beauty Original Web Series</a>
		</div>
		<div id="navGame">
		<a href="/games/fantastic-plastic-makeover">Addicted to Beauty Original Game</a>
		</div>
		<div id="navBoards">
		<a target="_blank" href="http://forums.oxygen.com/index.php?showforum=20">Chat On The Message Boards</a>
		</div>
		<div id="navAbout">
		<a href="/about-addicted-to-beauty">About The Show</a>
		</div>
		<div id="navShop" style="background-position: -285px 0px;cursor:default;">
		<a href="">Addicted to Beauty Shop</a>
		</div>
		</div>
	</div>