      <div id="micrositeHeader">
				<img src="http://www.oxygen.com/tvshows/movies/images/shell/MainHeader_07-01.jpg" usemap="#Map" />
      </div>
<map id="Map" name="Map">
		<area href="http://www.oxygen.com/tvshows/movies/schedule.aspx" coords="250,60,390,180" alt="Movies | Schedule" shape="rect">
		<area href="http://www.oxygen.com/tvshows/movies/default.aspx" coords="710,0,912,183" alt="Movies | Home" shape="rect">
 	</map>


      <div id="micrositeMenu" class="<?php print $node->type;?>">
		<div id="micrositeMenuCenter">
		<div id="navHome">
			<a href="http://www.oxygen.com/tvshows/movies/default.aspx"><span>home</span></a>
		</div>		
		<div id="navPhotos">
			<a href="http://www.oxygen.com/tvshows/movies/photos/July-2010-Birthdays.aspx"><span>movie photos</span></a>
		</div>
		<div id="navSchedule">
			<a href="http://www.oxygen.com/tvshows/movies/schedule.aspx"><span>movie schedule</span></a>
		</div>
		<div id="navExtras">
			<a href="http://www.oxygen.com/tvshows/movies/fun/"><span>movie fun</span></a>
		</div>
		<div id="navBoards">
			<a target="_blank" href="http://forums.oxygen.com/index.php?showforum=16">Chat On The Message Boards</a>
		</div>
		<div id="navBlogs">
			<a href="http://movies.oxygen.com/">Movie Blogs</a>
		</div>
<!--		<div id="navNews" style="background-position: -285px 0px;cursor:default;">
			<a href="">Addicted to Beauty Shop</a>
		</div> -->
		</div>
	</div>