<?php
// $Id$  crop_presets.module September 24, 2011 Randall Goya decibel.places
// Prefills Focus Crop & Resize values from Imagecache settings

/* get the node type */
if (!isset($thenodetype)){
if ('node' == arg(0)){
if (arg(2) != "edit") $thenodetype = str_replace('-', '_', arg(2)); // This is the node type
//if (arg(2) != "edit") $thenodetype = arg(2); // This is the node type
else if(is_numeric(arg(1))) {
  $node = node_load(arg(1));
  $thenodetype = $node->type;
}
}
}
//dsm('crop_presets');
//dsm($thenodetype);


/* if the node type is a promo */
if (strpos($thenodetype, 'promo') > 0)
{
$presets = imagecache_presets();
$thiswidth = $presets[$thenodetype]['actions'][0]['data']['width'];
$thisheight = $presets[$thenodetype]['actions'][0]['data']['height'];
//dsm(dprint_r($presets));
//dsm($thiswidth);
drupal_add_js('var cropw = ' . $thiswidth . '; var croph = ' . $thisheight . ';', 'inline');
	
//load script to run on node/add form
drupal_add_js(drupal_get_path('module', 'crop_presets') . '/crop_presets.js', 'module');

//load stylesheet on node/add form
drupal_add_css(drupal_get_path('module', 'crop_presets') . '/crop_presets.css', 'module');
}

/**
 * Add JS to the IMCE popup dialog
 *
 * Implementation of hook_form_formID_alter().
 */
function crop_presets_form_imce_fileop_form_alter(&$form, &$form_state) {
    drupal_add_js(drupal_get_path('module', 'crop_presets') . '/crop_presets_imce_form.js', 'module');
}

/**
 * Implementation of hook_nodeapi().
 */
function crop_presets_nodeapi(&$node, $op, $a3 = NULL, $a4 = NULL) {
 $item['data']['crop_rect'] = "0,0," . $thiswidth . "," . $thisheight;
}


/**
 * Implementation of hook_file_references().
 * see http://drupal.org/node/441280#comment-3095634
 */

function crop_presets_filefield_file_references($file) {
  return array('crop_presets_filefield' => 1);
}

/**
 * set module weight to load after imagecache module
 * see http://drupal.org/node/110238
 */
$weight = db_result(db_query("SELECT weight FROM {system} WHERE name = 'imagecache'"));
db_query("UPDATE {system} SET weight = %d WHERE name = 'crop_presets'", $weight + 1);