<div id="footer">
	<div id="mainFooterLogos">
			<div class="footerLogo" style="width:134px;">
				<a href="http://www.oxygenlive.com"><img src="/sites/all/themes/oxygenhomepage/images/oxygencom/oxylive.png" width="134" height="58" alt="oxygenlive"></a>
				<br><a href="http://www.oxygenlive.com">Chat, react, and interact LIVE with Oxygen stars and superfans.</a>
			</div>
			<div class="footerLogo" style="width:158px;">

				<a href="http://features.oxygen.com/obsessed/free-oxygenlive-app"><img src="/sites/all/themes/oxygenhomepage/images/oxygencom/oxy-mobile-app-footergraphic.png" width="158" height="58" alt="OxygenLive Mobile App"></a>
				<br><a href="http://features.oxygen.com/obsessed/free-oxygenlive-app">Download our OxygenLive app on your iPhone or iPad.</a>
			</div>
			<div class="footerLogo" style="width:130px;">
				<a href="http://www.shopoholic.com"><img src="/sites/all/themes/oxygenhomepage/images/oxygencom/shopoholic.png" width="130" height="58" alt="shopoholic"></a>
				<br><a href="http://www.shopoholic.com">Get gear, DVD, and more inspired by your fav Oxygen shows. Start shopping now.</a>
			</div>
			<div class="footerLogo" style="width:195px;">

				<a href="http://www.hormoneoscope.com"><img src="/sites/all/themes/oxygenhomepage/images/oxygencom/hormoneoscope.png" width="195" height="58" alt="hormoneoscope"></a>
				<br><a href="http://www.hormoneoscope.com">Download the mood predictor app for your desktop, Facebook or iPhone.</a>
			</div>


	</div>
	<div id="globalSubFooter">
			<span><a href="http://www.oxygen.com">Home</a>|</span>

			<span><a href="http://www.oxygen.com/tvshows/">TV Shows</a>|</span>
			<span><a href="http://www.oxygen.com/schedule/" target="_blank">Schedule</a>|</span>
			<span><a href="http://www.oxygen.com/games/">Games</a></span>
			<span><a href="http://www.oxygen.com/sweepstakes/">Sweepstakes</a>|</span>
			<span><a href="http://www.oxygen.com/legal/terms.aspx">Terms</a>|</span>			
			<span><a href="http://www.oxygen.com/legal/privacyPolicy.aspx">Privacy Policy</a>|</span>

			<span><a href="http://www.nbcuni.com/" target="_blank">Corporate Info</a>|</span>
			<span><a href="http://www.oxygen.com/legal/contact.aspx">Contact Us</a></span>
			<span><a href="http://nbc.researchresults.com/?s=64">Join NBCU Panel</a>|</span>
			<span><a href="http://www.comcast.com/independentprogramming" target="_blank">Independent Programming Report</a></span>
			<br><span style="color:#fff;">TM & Copyright © 1998-2011 Oxygen Media. All Rights Reserved</span>						
			
	</div>

</div><!--end footer-->
			
</div><!-- close globalWrapper -->
</div><!-- close mainBg -->
<script src="http://www.nbcudigitaladops.com/hosted/global.js"></script>

<!-- Kontera ContentLink(TM);-->
<script type='text/javascript'>

var dc_AdLinkColor = 'blue' ;
var dc_isBoldActive= 'no';
var dc_PublisherID = 136535 ;
</script>
<script type='text/javascript' src='http://kona.kontera.com/javascript/lib/KonaLibInline.js'>
</script>
<!-- Kontera ContentLink(TM) -->

<!-- iCompass tag ROS.  Needs to be removed on 8/4/2010 -->
<!-- <script language="javascript" src="http://core.insightexpressai.com/adServer/adServerESI.aspx?bannerID=168701"></script> -->

		<!-- comment test -->
			
		
		<script language="javascript" type="text/javascript" src="http://oxygen.com/js/omniture/s_wrapper.js"></script>

<!-- SiteCatalyst code version: H.2. Copyright 1997-2008 Omniture, Inc. and NBCU More info available at http://www.omniture.com -->
<script type="text/javascript" language="javascript">
	<!--
	s.prop3="Homepage";
	s.prop10="Oxygen Homepage";
	s.pageName=document.title;		//// page name, auto reads from the page TITLE tag
	/************* DO NOT ALTER ANYTHING BELOW THIS LINE ! **************/
	var s_code=s.t(); if(s_code) document.write(s_code)
	//-->

</script><script type="text/javascript" language="javascript">
	<!--
	if(navigator.appVersion.indexOf('MSIE') >= 0) document.write(unescape('%3C')+'\!-'+'-')
	//-->

</script><!--/DO NOT REMOVE/-->
<!-- End SiteCatalyst code version: H.2. -->



		
		<script src="/js/objects/promoController_Q3.js" type="text/javascript"></script>	
		<script src="/js/railsAd.js" type="text/javascript"></script> 
			
			<!--gmkey:a45f89c9-->

	<script type=""text/javascript"">
document.write('<sc'+'ript language=\'JavaScript1.1\' src=""http://ad.doubleclick.net/adj/nbcu.oxygen/obsessed_242805190jul31;site=oxygen;sect=obsessed;sub=242805190jul31;genre=;daypart=primetime;!category=obsessed;!category=js;!category=scifi;network=tvn;sz=1x1;tagtype=js;uri=;pos=10;tile=10;ord=' + randDARTNumber + '?""></s'+'cript>');
</script>
