 

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN"
	"http://www.w3.org/TR/html4/strict.dtd">
<HTML>
	<HEAD>

				<title>Homepage | Online TV Shows | Reality TV Shows | Stars & Fans | Live Out Loud, Oxygen </title>
		 <!-- RED aLERT - DO NOT REMOVE -->
		<link rel="icon" href="/favicon.ico" />
		<meta name="description" content="Watch reality TV shows online and see episodes of reality television for free. See episodes of reality TV shows online only from Oxygen." />
		<meta name="keywords" content="Oxygen Live Out Loud, The Naughty Kitchen, Bad Girls Club, Snapped, America’s Next Top Model, Obsessed, Tori and Dean Home Sweet Hollywood, Addicted to Beauty, Dance Your Ass Off, Janice Dickinson Modeling Agency, Pretty Wicked, Captured, Talk Sex, Deion and Pilar Prime Time Love, Janice and Abbey, Reality TV Shows, Online Reality TV Videos, Reality TV Blogs, Reality TV Photos, QuizOlicious, ShopOholic, Movie Lounge, Sounds Like Oxygen, Don’t Miss This Week, Celebrity Gossip" />

		<!-- <meta name="keywords" content="reality tv show, tv shows online, reality television casting, stars, fans, reality tv, tv shows online, free tv shows, reality television, reality tv show, reality tv shows, fans of reality tv" /> -->
		<meta name="robots" content="noodp,noydir" />

		<!-- Begin stylesheets -->
		<link rel="stylesheet" href="/common/css/common.css" type="text/css" />
		<link rel="stylesheet" href="/common/css/header.css" type="text/css" /> 
		<link rel="stylesheet" href="homepage.css" type="text/css" />
		<link rel="stylesheet" href="/common/css/footer.css" type="text/css" />
		<link rel="stylesheet" href="/common/css/shell.css" type="text/css" />		
		<!-- End stylesheets -->

<!--[if IE 6]>
	<link rel="stylesheet" type="text/css" href="homepage_IE6.css" />
<![endif]-->		
		<!-- Begin javascripts -->
		<script src="/js/util.js" type="text/javascript"></script>
		<script src="/js/objects/jquery.js" type="text/javascript"></script>
		<script src="/js/objects/jquery.cycle.all.js" type="text/javascript"></script>
		<script type="text/javascript" src="/js/objects/jScrollPane.js"></script>	
		<script src="/js/objects/oxygen_embed_player.js" type="text/javascript"></script>
		<script src="/temp/oxygenlive/jquery.modal.js" type="text/javascript"></script>

		<link rel="stylesheet" href="/temp/oxygenlive/modal.css" type="text/css" />
		
		
<!-- added 6/12 prior to The Glee Project premiere -->

<script src="http://core.insightexpressai.com/adServer/adServerESI.aspx?bannerID=179219"></script>
 
<script src="http://core.insightexpressai.com/adServer/adServerESI.aspx?bannerID=179219"></script>
 
<script src="http://core.insightexpressai.com/adServer/adServerESI.aspx?bannerID=179269"></script>


		

	</HEAD>

	<body id="oxygenHome">



	
	<img class="pxlTRCK" src="http://leadback.advertising.com/adcedge/lb?site=695501&srvc=1&betr=oxygen_cs=1&betq=7764=398690" width="1" height="1" border="0">

		
<script src="http://www.nbcudigitaladops.com/hosted/global_header.js"></script>


<div id="mainBg">
		<div id="globalWrapper">
		
			<div id="oxyHeader">

				<div id="topHeaderHalf" style="background-color: #000000;">
					<div id="Oxygenlogo" style="padding:0 0 0 450px;">
						<span style="display:none;">Oxygen</span>

						<a href="http://www.oxygen.com/"><img src="http://www.oxygen.com/common/images/_global2010/oxygen_logo_copy.jpg" alt="" width="120" height="90" border="0"/></a>
					</div>
					<ul id="globalNav"><!--Global Navigation-->
	
						<li class="navHome"><a href="/default.aspx" style="display:block;height:45px;width:28px;text-indent:-9999px">Home</a></li>

						<li class="navShows"><a href="/tvshows/" style="display:block;height:45px;width:100px;text-indent:-9999px">Shows</a></li>
						<li class="navBlogs"><a href="http://features.oxygen.com/allsite-blogs" style="display:block;height:45px;width:98px;text-indent:-9999px">Blogs</a></li>
						<li class="navPhotos"><a href="http://photos.oxygen.com/" style="display:block;height:45px;width:115px;text-indent:-9999px">Photos</a></li>
						<li class="navVideos"><a href="http://video.oxygen.com/" style="display:block;height:45px;width:107px;text-indent:-9999px">Video</a></li>
						<li class="navFullEps"><a href="http://www.oxygen.com/full-episodes" style="display:block;height:45px;width:214px;text-indent:-9999px">Full Episodes</a></li>
					</ul>

				</div>	<!-- end topHeaderHalf -->
				<div id="bottomHeaderHalf" style="width:984px; margin-left:0px;">
					<ul id="globalSubNav" style="width:984px;">
						<li class="navSchedule"><a href="http://www.oxygen.com/schedule">Schedule</a></li>
						<li class="navBoards"><a href="http://forums.oxygen.com">Message Boards</a></li>					
						<li class="navGames"><a href="http://www.oxygen.com/games/">Games</a></li>
						<li class="navShop"><a href="http://www.shopoholic.com">Shop</a></li>						
						<li class="navMobile"><a href="http://www.oxygen.com/mobile">Mobile</a></li>	
						<li><form method="post" action="http://search.oxygen.com/search-redirect">

								<input   type="text" name="s" style="font-size:9px;margin:8px 0 0 66px;padding:2px 0px;float:left;display:inline;background-color:#fcfcfc;width:170px;height:8px;border:none;" maxlength="254">
								<input id="searchBtn" type="image" id="goButton" name="btnG" value="Search" src="/common/images/_global/navigation/search_icon.gif" width="24" height="12">
							</form>	</li>					
					<!-- 	<div class="navGames"><a href="http://www.oxygen.com/schedule">Games</a></div>										
						<div class="navShop"><a href="http://www.oxygen.com/schedule">Shop</a></div>															
						<div class="navMobile"><a href="http://www.oxygen.com/schedule">Mobile</a></div> -->
						<!-- <div class="globalSearch"> 
							<span style="float:left;width:80px;">search here</span>
							<form method="post" action="http://search.oxygen.com/search-redirect">
								<input   type="text" name="s" style="margin:0px;padding:2px 0px;float:left;display:inline;background-color:#fcfcfc;width:280px;height:20px;border:none;" maxlength="254">
								<input id="searchBtn" type="image" id="goButton" name="btnG" value="Search" src="/common/images/_global/navigation/searchBtn.gif" width="35" height="20">
							</form>							
								 
						</div> --><!-- end global search -->
					
					</ul>
	
					<div id="adExpander">
						<!--Begin Top AD 728x90-->
							

<div id="topAdBlock">
	<script type="text/javascript" language="javascript">
	//<![CDATA[
	document.write('<scr' + 'ipt language="javascript" type="text/javascript" src="http://iv.doubleclick.net/adj/nbcu.oxygen/oxygen_home;site=oxygen;sect=home;pageid=hp;dcopt=ist;!category=oxygen;!category=home;sz=728x90,970x66;tile=1;pos=1;' + (top.__nbcudigitaladops_dtparams||'') + 'ord=' + randDARTNumber + '?"></scr' + 'ipt>');//]]>

</script><noscript><a target="_blank" href="http://iv.doubleclick.net/jump/nbcu.oxygen/oxygen_home;site=oxygen;sect=home;pageid=hp;!category=oxygen;!category=home;sz=728x90,970x66;tile=1;pos=1;ord=123456a?"><img src="http://iv.doubleclick.net/ad/nbcu.oxygen/oxygen_home;site=oxygen;sect=home;pageid=hp;!category=oxygen;!category=home;sz=728x90,970x66;tile=1;pos=1;ord=123456a?" border="0" alt="" /></a></noscript><!--Oxygen.DotCom.Advertising.DARTAdTag+DARTAdTagControl-->
</div>

						<!--End Top 728x90-->	
						<script type="text/javascript">
						$('#topAdBlock a:last').css('display','none');
						</script>
					</div>
				</div> <!-- End bottomHeaderHalf-->
			</div> <!-- end OxyHeader -->

			
		

			
			<script type="text/javascript">
				var _pagePath = baseSiteURL+"/Default.aspx".toLowerCase();
			</script>

