      <div id="micrositeHeader">
		<img src="<?php print $pot;?>/images/BPLV_header_prepremiere.jpg" />
      </div>

      <div id="micrositeMenu" class="<?php print $node->type;?>">
		<div id="micrositeMenuCenter">

		<div id="navHome">
		<a href="/">Bachelorette Party Home</a>
		</div>
		<div id="navMeet">
		<!-- <a href="/meet-the-cast-bp">Bachelorette Party Bios</a> -->
		<div class="navPlaceholder"> </div>
		</div>		
		<div id="navPhotos">
		<a href="/bp-gallery-redirect-page">Bachelorette Party Photo Gallery</a>
		</div>
		<div id="navVideos">
		<!-- <a href="">Bachelorette Party Videos</a> -->
		<div class="navPlaceholder"> </div>
		</div>
		<div id="navBlogs">
		<!-- <a href="/blogs/bp">Bachelorette Party Blogs</a> -->
		<div class="navPlaceholder"> </div>		</div>
		<div id="navBoards">
		<!-- <a href="http://forums.oxygen.com/index.php?showforum=26">Chat On The Bachelorette Party Message Boards</a> -->
		<div class="navPlaceholder"> </div>		</div>
		<div id="navOxy">
		<!-- <a href="#">Bachelorette Party on OxygenLive</a> -->
		<div class="navPlaceholder"> </div>		</div>
		<div id="navAbout">
		<a href="/about-bachelorette-party">About The Bachelorette Party</a>
		</div>
		<div id="navSweeps">
		<!-- <a href="#">Bachelorette Party Glam Sweeps</a> -->
		<div class="navPlaceholder"> </div>		</div>		



		</div>
	</div>