      <div id="micrositeHeader">
		<img src="http://www.oxygen.com/tvshows/torianddean/images/tor_headerBG.jpg" />
      </div>



      <div id="micrositeMenu" class="<?php print $node->type;?>">
		<div id="navHome">
		<a href="/">Tori and Dean Home</a>
		</div>
		<div id="navMeet">
		<a href="/meet-the-cast">Meet The Cast</a>
		</div>
		<div id="navPhotos">
		<a href="http://www.oxygen.com/tvshows/prettywicked/includes/photocurrent.html">Photo Gallery</a>
		</div>
		<div id="navBlogs">
		<a href="http://www.oxygen.com/tvshows/prettywicked/includes/blogcurrent.html">Tori and Dean Blogs</a>
		</div>
		<div id="navVideos">
		<a href="http://o2.oxygen.com/player/?fid=1010881">Tori and Dean Videos</a>
		</div>
		<div id="navRecaps">
		<a href="/recaps/episode1">Tori and Dean Episode Recaps</a>
		</div>
		<div id="navExtras">
		<a href="/extras" target="_blank">Tori and Dean Shop</a>
		</div>
		<div id="navBoards">
		<a target="_blank" href="http://forums.oxygen.com/index.php?showforum=17">Chat On The Message Boards</a>
		</div>
		<div id="navAbout">
		<a href="/about-the-show">About The Show</a>
		</div>
      </div>