      <div id="micrositeHeader">
		<img src="<?php print $pot;?>/images/hbs_header_sonew.jpg" />
      </div>



      <div id="micrositeMenu" class="<?php print $node->type;?>">
		<div id="micrositeMenuCenter">
		<div id="navHome">
		<a href="/">Hair Battle Spectacular Home</a>
		</div>
		<div id="navMeet">
		<a href="/meet-the-cast-hbs">Hair Battle Spectacular Bios</a>
		</div>		
		<div id="navPhotos">
		<a href="/hbs-gallery-redirect-page">Hair Battle Spectacular Photo Gallery</a>
		</div>
		<div id="navVideos">
		<a href="http://video.oxygen.com/shows/hair_battle_spectacular">Hair Battle Spectacular Videos</a>
		</div>
		<div id="navBlogs">
		<a href="/blogs/hbs">Hair Battle Spectacular Blogs</a>
		</div>
		<div id="navBoards">
		<a href="http://forums.oxygen.com/index.php?showforum=26">Chat On The Hair Battle Spectacular Message Boards</a>
		</div>
		<div id="navAbout">
		<a href="/about-hair-battle-spectacular">About The Hair Battle Spectacular</a>
		</div>
		<div id="navShop">
		<a href="http://www.shopoholic.com">Hair Battle Spectacular Shop</a>
		</div>
		</div>
	</div>