      <div id="micrositeHeader">
		<img src="<?php print $pot;?>/images/GP-Header.jpg" />
      </div>



      <div id="micrositeMenu" class="<?php print $node->type;?>">
		<div id="micrositeMenuCenter">
		<div id="navHome">
		<a href="/">The Glee Project Home</a>
		</div>
		<div id="navMeet">
		<a href="http://thegleeproject.oxygen.com/meet-the-cast-gleeproj">The Glee Project Cast Bios</a>
		</div>
		<div id="navPhotos">
		<a href="http://thegleeproject.oxygen.com/thegleeproject-gallery-redirect-page">Glee Project Photo Gallery</a>
		</div>
		<div id="navVideos">
		<a href="http://video.oxygen.com/shows/the_glee_project">Glee Project Videos</a>
		</div>
		<div id="navBlogs">
		<a href="http://thegleeproject.oxygen.com/blogs/GLEEProj">Glee Project Blogs</a>
		</div>
		<div id="navBoards">
		<a href="http://forums.oxygen.com/index.php?showforum=31">Chat On The Glee Project Message Boards</a>
		</div>
		<div id="navOxy">
		<a href="http://www.oxygenlive.com/event.php?show=TheGleeProject&coast=EC">The Glee Project on OxygenLive</a>
		</div>
		<div id="navAbout">
		<a href="http://thegleeproject.oxygen.com/about-thegleeproject">About The Glee Project</a>
		</div>
		<div id="navShop">
		<a href="http://www.shopoholic.com/eSource/PK/ecom/eSource/default/default.aspx?store=OXYv3">The Glee Project Shop</a>
		</div>

		</div>
	</div>