      <div id="micrositeHeader">
		<img src="/sites/all/themes/torianddean/images/tor_headerBG.jpg" />
      </div>



      <div id="micrositeMenu" class="<?php print $node->type;?>">
		<div id="navHome">
		<a href="/">Tori and Dean Home</a>
		</div>
		<div id="navMeet">
		<a href="/meet-the-cast">Meet The Cast</a>
		</div>
		<div id="navMommywood">
		<a href="#" onClick="return false;" style="background-position: -194px 0px;">Road Trip</a>
		</div>		
		<div id="navPhotos">
		<a href="/tori-gallery-redirect-page">Photo Gallery</a>
		</div>
		<div id="navBlogs">
		<a href="/td-blog-redirect-page">Tori and Dean Blogs</a>
		</div>
		<div id="navVideos">
		<a href="http://o2.oxygen.com/player/?fid=1210554">Tori and Dean Videos</a>
		</div>
		<!-- <div id="navRecaps">
		<a href="" style="background-position: -501px 0px;">Tori and Dean Episode Recaps</a>
		</div> -->
		<div id="navBoards">
		<a target="_blank" href="http://forums.oxygen.com/index.php?showforum=4">Chat On The Message Boards</a>
		</div>
		<div id="navAbout">
		<a href="/about-the-show">About The Show</a>
		</div>
		<div id="navShop">
		<a href="http://shop.oxygen.com/b2c/PK/ecom/ecomEnduser/default/defaultNF.aspx?store=oxygen">Shop</a>
		</div>
	</div>