      <div id="micrositeHeader">
		<img src="<?php print $pot;?>/images/Paris_header_06_16_11.jpg" />
      </div>

      <div id="micrositeMenu" class="<?php print $node->type;?>">
		<div id="micrositeMenuCenter">
		<div id="navHome">
		<a href="/">The World According to Paris Home</a>
		</div>
		<div id="navMeet">
		<a href="http://the-world-according-to-paris.oxygen.com/meet-the-cast-paris">The World According to Paris Bios</a> 
		</div>		
		<div id="navPhotos">
		<a href="/paris-photo-gallery-redirect-page">The World According to Paris Photo Gallery</a>
		</div>
		<div id="navVideos">
		<a href="http://video.oxygen.com/shows/the_world_according_to_paris">The World According to Paris Videos</a>
		</div>
		<div id="navBlogs">
		<a href="http://the-world-according-to-paris.oxygen.com/blogs/paris">The World According to Paris Blogs</a>
		</div>
		<div id="navBoards">
		<a href="http://forums.oxygen.com/index.php?showforum=34">Chat On The The World According to Paris Message Boards</a>
		</div>
		<div id="navOxy">
		<a href="http://www.oxygenlive.com/event.php?show=Paris&coast=EC">The World According to Paris on OxygenLive.com</a>
		</div>
		<div id="navBroadcastr">
		<a href="http://the-world-according-to-paris.oxygen.com/listen-to-paris-on-broadcastr">The World According to Paris - Broadcastr</a>
		</div>
		<div id="navAbout">
		<a href="/about-paris">About The The World According to Paris Show</a>
		</div>

		</div>
	</div>

