<?php
/** Snippet to schedule main header image based on server time ***/
$pathadd = '';


?>
      <div id="micrositeHeader">
		<img src="<?php print $pot;?>/images/lovegames_header_8_11.jpg" alt="Love Games on Oxygen" />
      </div>



      <div id="micrositeMenu" class="<?php print $node->type;?>">
		<div id="micrositeMenuCenter">
		<div id="navHome">
		<a href="/">Love Games Home</a>
		</div>
		<div id="navMeet">
		<a href="/meet-the-cast-lg">Meet the Cast- Love Games</a>
		</div>		
		<div id="navPhotos">
		<!-- <a href="/lovegames-gallery-redirect-page">Love Games Photo Gallery</a> -->
		<a href="http://love-games.oxygen.com/lovegames/photos/episode-7-and-then-there-were-two">Love Games Photo Gallery</a>
		</div>
		<div id="navVideos">
		<a href="http://video.oxygen.com/shows/love_games_season_2">Love Games Videos</a>
		</div>
		<div id="navBlogs">
		<a href="http://love-games.oxygen.com/blogs/lovegames">Love Games Blogs</a>
		</div>
		<div id="navCasting">
		<a href="http://features.oxygen.com/outloud/blog/entertainment/havent-found-your-bad-girl-princess-yet">Love Games Casting</a>
		</div>
		<div id="navBoards">
		<a href="http://forums.oxygen.com/index.php?showforum=24">Chat On The Love Games Message Boards</a>
		</div>
		<div id="navOxy">
		 <a href="http://www.oxygenlive.com/event.php?show=LoveGames&coast=EC">Love Games on OxygenLive</a>
		</div>
		<div id="navAbout">
		<a href="/about-love-games">About The Love Games Show</a>
		</div>
		<div id="navShop">
		<a href="http://www.shopoholic.com" target="_blank">Love Games Shop</a>
		</div>
		</div>
	</div>