	<style type="text/css">
		/* highlighting of "shows" in global nav */
		.global_navShows a {background-position:-63px 60px;}
	</style>

      <div id="micrositeHeader">
 <? if(date("YmdHi") < "200909160001"){ ?>

<img src="<?php print $pot;?>/images/mainHeader_sonew.jpg" /> 

 <? }else{  ?>


<img src="<?php print $pot;?>/images/mainHeader_noegg.jpg" />

 <? } ?>
		
      </div>



      <div id="micrositeMenu" class="<?php print $node->type;?>">
		<div id="micrositeMenuCenter">
		<div id="navHome">
		<a href="/">Addicted to Beauty Home</a>
		</div>
		<div id="navMeet">
		<a href="/meet-the-cast-atb">Meet The Cast</a>
		</div>		
		<div id="navPhotos">
		<a href="/atb-gallery-redirect-page">Photo Gallery</a>
		</div>
		<div id="navBlogs">
		<a href="/atb-blog-redirect-page">Addicted to Beauty Blogs</a>
		</div>
		<div id="navVideos">
		<a href="http://o2.oxygen.com/player/?fid=1141806">Addicted to Beauty Videos</a>
		</div>
		<div id="navWebSeries">
		<a href="/addicted-to-gary">Addicted to Beauty Original Web Series</a>
		</div>
		<div id="navGame">
		<a href="/games/fantastic-plastic-makeover">Addicted to Beauty Original Game</a>
		</div>
		<div id="navBoards">
		<a target="_blank" href="http://forums.oxygen.com/index.php?showforum=20">Chat On The Message Boards</a>
		</div>
		<div id="navAbout">
		<a href="/about-addicted-to-beauty">About The Show</a>
		</div>
		<div id="navShop">
		<a href="http://www.shopoholic.com/b2c/PK/ecom/ecomEnduser/items/2-S0-lV1ATB-lV2OXY.aspx" target="_blank">Addicted to Beauty Shop</a>
		</div>
		</div>
	</div>