      <div id="micrositeHeader">
		<img src="<?php print $pot;?>/images/RRS_noeggs.jpg" />
      </div>


      <div id="micrositeMenu" class="<?php print $node->type;?>">
		<div id="micrositeMenuCenter">
		<div id="navHome">
		<a href="/">Running Russell Home</a>
		</div>
		<div id="navMeet">
		<a href="/meet-the-cast-rrs">Running Russell Bios</a>
		</div>		
		<div id="navPhotos">
		<a href="/russell-gallery-redirect-page">Running Russell Photo Gallery</a>
		</div>
		<div id="navVideos">
		<a href="http://video.oxygen.com/shows/running_russell_simmons">Running Russell Videos</a>
		</div>
		<div id="navBlogs">
		<a href="http://running-russell.oxygen.com/blogs/russell">Running Russell Blogs</a>
		</div>
		<div id="navBoards">
		<a href="http://forums.oxygen.com/index.php?showforum=30">Chat On The Running Russell Message Boards</a>
		</div>
		<div id="navAbout">
		<a href="/about-running-russell">About Running Russell</a>
		</div>
		</div>
	</div>