	<style type="text/css">
		/* highlighting of "shows" in global nav */
		.global_navShows a {background-position:-63px 60px;}
	</style>

      <div id="micrositeHeader">
		<img src="<?php print $pot;?>/images/mainHeader.jpg" /> 
	
      </div>



      <div id="micrositeMenu" class="<?php print $node->type;?>">
		<div id="micrositeMenuCenter">
		<div id="navHome">
		<a href="/">Naughty Kitchen Home</a>
		</div>
		<div id="navMeet">
		<a href="/meet-the-cast-nk">Meet The Cast</a>
		</div>		
		<div id="navPhotos">
		<a href="/nk-gallery-redirect-page">Photo Gallery</a>
		</div>
		<div id="navVideos">
		<a href="http://o2.oxygen.com/player/?fid=1153044">Naughty Kitchen Videos</a>
		</div>
		<div id="navWebSeries">
		<a href="/recipes-from-the-naughty-kitchen-with-chef-blythe-beck">Naughty Kitchen Original Web Series</a>
		</div>
		<div id="navRecipes">
		<a href="http://features.oxygen.com/recipes">Naughty Kitchen Recipes</a>
		</div>
		<div id="navBlogs">
		<a href="/nk-blog-redirect-page">Naughty Kitchen Blogs</a>
		</div>
		<div id="navBoards">
		<a href="http://forums.oxygen.com/index.php?showforum=21" target="_blank">Chat On The Message Boards</a>
		</div>
		<div id="navAbout">
		<a href="/about-naughty-kitchen">About The Show</a>
		</div>
		<div id="navShop">
		<a href="http://www.shopoholic.com/b2c/PK/ecom/ecomEnduser/items/2-S0-lV1NaughtyK-lV2OXY.aspx" target="_blank">Shop</a>
		</div>
		</div>
	</div>