      <div id="micrositeHeader">
		<img src="<?php print $pot;?>/images/JC_showsiteheader4.jpg" />
      </div>



      <div id="micrositeMenu" class="<?php print $node->type;?>">
		<div id="micrositeMenuCenter">
		<div id="navHome">
		<a href="/">Jersey Couture Home</a>
		</div>
		<div id="navMeet">
		<a href="/meet-the-cast-jersey-couture">Jersey Couture Bios</a>
		</div>		
		<div id="navPhotos">
		<a href="/jc-photo-gallery-redirect-page">Jersey Couture Photo Gallery</a>
		</div>
		<div id="navVideos">
		<a href="http://video.oxygen.com/shows/jersey_couture">Jersey Couture Videos</a>
		</div>
		<div id="navBlogs">
		<a href="/blogs/jerseycouture">Jersey Couture Blogs</a>
		</div>
		<div id="navFluffMe">
		<a href="/Fluff-Me-Community">Fluff Me Community</a>
		</div>
		<div id="navBoards">
		<a href="http://forums.oxygen.com/index.php?showforum=25">Chat On The Jersey Couture Message Boards</a>
		</div>
		<div id="navAbout">
		<a href="/about-jersey-couture">About The Jersey Couture Show</a>
		</div>
		<div id="navShop">
		<a href="#">Jersey Couture Shop</a>
		</div>
		<div id="navSweeps">
		<a href="http://jersey-couture.oxygen.com/jerseycouture/photos/sweepstakes-winner">Sweeps</a>
		</div>
		<div id="navRecaps">
		<a href="http://o2.oxygen.com/player/?fid=1231373">Recaps</a>
		</div>
		</div>
	</div>