	<style type="text/css">
		/* highlighting of "shows" in global nav */
		.global_navShows a {background-position:-63px 60px;}
	</style>

      <div id="micrositeHeader">
		<img src="<?php print $pot;?>/images/mainHeader.jpg" />
      </div>



      <div id="micrositeMenu" class="<?php print $node->type;?>">
		<div id="navHome">
		<a href="/">Dance Your Ass Off Home</a>
		</div>
		<div id="navMeet">
		<a href="/meet-the-cast-dyao">Meet The Cast</a>
		</div>
		<div id="navPhotos">
		<a href="/dyao-gallery-redirect">Photo Gallery</a>
		</div>
		<div id="navVideos">
		<a href="http://o2.oxygen.com/player/?fid=1100245">Dance Your Ass Off Videos</a>
		</div>
		<div id="navBlogs">
		<a href="/dyao-blog-redirect">Dance Your Ass Off Blogs</a>
		</div>
		<div id="navFitness">
		<a href="/dyao/fit_club" >Dance Your Ass Off Fit Club</a>
		</div>
		<div id="navExtras">
		<a href="/dyao/extras">Extras</a>
		</div>
		<div id="navBoards">
		<a target="_blank" href="http://forums.oxygen.com/index.php?showforum=19">Chat On The Message Boards</a>
		</div>
		<div id="navAbout">
		<a href="/about-dyao">About The Show</a>
		</div>
		<div id="navCasting">
		<a href="/dance-your-ass-off-casting-newsletter-signup">Show Casting</a>
		</div>
		<div id="navShop">
		<a href="http://www.shopoholic.com/b2c/PK/ecom/ecomEnduser/items/2-S0-lV1DYAO-lV2OXY.aspx" target="_blank">Shop the DYAO store</a>
		</div>
      </div>