<?

$weeklyEpisodes = array(
	'week-0' => '2011-07-21 11:00:00',
	'week-1' => '2011-07-28 11:00:00',
	'week-2' => '2011-08-04 11:00:00',
	'week-3' => '2011-08-11 11:00:00',
	'week-4' => '2011-08-18 11:00:00',
	'week-5' => '2011-08-25 11:00:00'
);

$currentTime = time();

if($currentTime > strtotime($weeklyEpisodes['week-0'])) $currentWeek = 'week-1';

if($currentTime > strtotime($weeklyEpisodes['week-1'])) $currentWeek = 'week-1';

if($currentTime > strtotime($weeklyEpisodes['week-2'])) $currentWeek = 'week-2';

if($currentTime > strtotime($weeklyEpisodes['week-3'])) $currentWeek = 'week-3';

if($currentTime > strtotime($weeklyEpisodes['week-4'])) $currentWeek = 'week-4';

if($currentTime > strtotime($weeklyEpisodes['week-5'])) $currentWeek = 'week-5';


$currentWeek = strtotime($weeklyEpisodes[$currentWeek]);

$start = date("F j, Y", strtotime('+4 days', $currentWeek));
$end = date("F j, Y", strtotime('+5 days', $currentWeek));
$dayAfter = date("F j, Y", strtotime('+6 days', $currentWeek));

?>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:og="http://ogp.me/ns#"
      xmlns:fb="http://www.facebook.com/2008/fbml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>The Bad Girls Club Talent Call Sweepstakes Official Rules | The Bad Girls Club | Oxygen</title>

<meta http-equiv="content-type" content="text/html; charset=iso-8859-1" />
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="description" content="The Bad Girls Club Talent Call Sweepstakes Official Rules <?=$start ?> — <?=$end ?> Show Title for Web Page Title:&amp;nbsp; The Bad Girls Club" />
</head>
<body>


<div style="padding:10px;">
	<p style="text-align:center; font-size:15px;">The  Bad Girls Club Talent Call Sweepstakes<br>
		Official Rules<br>
	<strong><?=$start ?>&mdash;<?=$end ?></strong></p>
	<p><strong>PRELIMINARY INFORMATION: </strong>NO PURCHASE  NECESSARY. A purchase will not improve your chances of winning. Void where  prohibited. The Bad Girls Club Talent Call  Sweepstakes (“Sweepstakes”) will  begin on <?=$start ?> at 9:00 PM ET and end on <?=$end ?> at 1:00 AM ET  (“Sweepstakes Period”). All times in the Sweepstakes refer to Eastern Time  (“ET”). Odds of winning depend upon the number of eligible Entries (as  defined below) received. Sweepstakes is subject to all applicable federal,  state and local laws.</p>
	<p><strong>ELIGIBILITY:</strong> Open only to permanent,  legal United States (“U.S.”) residents who are physically residing in one (1)  of the fifty (50) U.S. or the District of Columbia (excluding Puerto Rico,  Guam, the U.S. Virgin Islands and other U.S. territories) and who are eighteen  (18) years of age or older and have reached the age of majority in their state  of residence as of the start of the Sweepstakes Period. Entrants must have a valid U.S. Social Security Number or a valid  U.S. personal tax identification number. Officers, directors, and employees of Sweepstakes Entities (as defined  below), members of these persons’ immediate families (spouses and/or parents,  children, and siblings, and their spouses, regardless of where they reside),  and/or persons living in the same households as these persons (whether or not  related thereto) are not eligible to enter or win the Sweepstakes. Sweepstakes  Entities, as referenced herein, shall include Oxygen Media, LLC  (“Oxygen”), 75 Ninth Avenue, New York, NY 10011 and NBCUniversal Media, LLC, 30  Rockefeller Plaza, New York, NY 10112 (collectively, “Sponsors”), and their respective parent, subsidiary, and  affiliate companies, and their administrative, advertising, and promotion agencies, and any other entity involved in the development,  administration, promotion, or implementation of the Sweepstakes.</p>
	<p><strong>TO ENTER:</strong> To enter the Sweepstakes, during the Sweepstakes Period visit Oxygen.com (the “Website”), click on  the Sweepstakes link, and follow the provided instructions to complete and  thereafter submit the Entry form, which includes your name, address, telephone  number, email address, and date of birth (“Entry”). As part of the Entry, you  will be asked to submit a code word (“Code Word”), which can be found by  watching “The Bad Girls Club” on Oxygen on <?=$start ?> at 9:00 PM ET/PT.  Check your local listings to confirm channel and time. <strong>You do not have to enter the correct Code Word to be entered in the  Sweepstakes.  Incorrect entry of Code Word will not affect your chances of winning the  Sweepstakes. </strong>All Entries become the property of Sponsors, and will  not be acknowledged. <strong></strong></p>
	<p><strong>Entries  must be received before <?=$end ?> at 1:00 AM ET to be eligible for the  Sweepstakes.</strong> Sponsors’ computer  shall be the official timekeeper for all matters related to this Sweepstakes. You  may enter once during the  Sweepstakes Period. Multiple Entries  received from any person or email address beyond this limit will void all such  additional Entries. Entries generated by a script, macro, or other  automated means will be disqualified.<strong> </strong>Entries that are incomplete, garbled,  corrupted, or unintelligible for any reason, including, but not limited to,  computer or network malfunction or congestion, are  void and will not be accepted. In case of a dispute over the identity of an entrant, the  authorized account holder of the email address used to enter will be deemed to  be the entrant. “Authorized account holder” is defined as the person who is  assigned to an email address by an Internet access provider, online service  provider or other organization that is responsible for assigning email  addresses for the domain associated with the submitted email address.&nbsp;Entry constitutes permission (except where prohibited by  law) to use entrant’s name, city, state, likeness, image, and/or voice for  purposes of advertising, promotion, and publicity in any and all media now or  hereafter known, throughout the world in perpetuity, without additional compensation,  notification, permission, or approval.  <strong></strong></p>
	<p><strong>PRIVACY:</strong> Entrants will have the opportunity to  receive information from Oxygen and selected partners by checking the  appropriate box(es). If, at any time, you no longer wish to receive materials  from Oxygen or our partners, please go to Oxygen’s privacy policy, located at <u>http://www.oxygen.com/legal/privacyPolicy.aspx</u>,  or the applicable partner’s privacy policy, and follow the procedures  indicated.</p>
	<p><strong>WINNER  SELECTION AND NOTIFICATION:</strong> On or about <?=$dayAfter ?>, one (1) potential Winner (as defined below) will  be selected in a random drawing by representatives of Sponsors from all  eligible Entries received during the Sweepstakes Period. Sponsors will make two (2) attempts to notify potential Winner at the  phone number and/or email address submitted at the time of Entry.<strong> </strong>Potential<strong> </strong>Winner may be  required to execute and return an affidavit of eligibility, release of  liability, and, except where prohibited, publicity release (collectively,  “Sweepstakes Documents”) within two (2) days of such notification.  Noncompliance within this time period will result in disqualification, and, at  Sponsors’ sole discretion an alternate potential Winner may be selected from  the remaining eligible Entries. If potential Winner cannot be reached, is found  to be ineligible, cannot or does not comply with these Official Rules, or if  prize or prize notification is returned as undeliverable, potential Winner will  be disqualified and time permitting, at Sponsors’ sole discretion, an alternate  potential Winner may be selected from the remaining eligible Entries.  </p>
	<p><strong>PRIZE:</strong> There will be one (1) prize awarded (“Prize”) to winner (“Winner”). Prize will  consist of the following: one (1) phone call with a Bad Girls Club Season 7  cast member of the Winner’s choosing, subject to that cast member’s  availability. Phone call shall be a minimum of five (5) minutes long and date and/or time is subject to  change. Estimated Retail Value (“ERV”) of Prize is zero dollars  ($0).  </p>
	<p>All details of  Prize will be determined by Sponsors in their sole discretion. Sponsors reserve  the right to substitute a similar Prize (or Prize element) of comparable or  greater value. All taxes and other expenses, costs, or fees associated with the  acceptance and/or use of Prize are the sole responsibility of Winner. Prize  cannot be transferred by Winner or redeemed for cash and is valid only for the  items detailed above, with no substitution of Prize by Winner. If Prize is  unclaimed within a reasonable time after notification from Sponsors, as  determined by Sponsors in their sole discretion, it will be forfeited, and time permitting, an alternate Winner may  be selected from the remaining eligible Entries at Sponsors’ sole  discretion.  </p>
	<p><strong>CONDITIONS: </strong>By entering the  Sweepstakes, each entrant agrees for entrant and for entrant’s heirs,  executors, and administrators (a) to release and hold harmless Sweepstakes  Entities and their respective officers, directors, and employees (collectively,  “Released Parties”) from any liability, illness, injury, death, loss,  litigation, or damage that may occur, directly or indirectly, whether caused by  negligence or not, from such entrant’s participation in the Sweepstakes and/or  his/her acceptance, possession, use, or misuse of Prize or any portion thereof  (including any travel related thereto); (b) to indemnify Released Parties from any and all  liability resulting or arising from the Sweepstakes and to hereby  acknowledge that Released Parties have neither made nor are in any manner  responsible or liable for any warranty, representation, or guarantee, express  or implied, in fact or in law, relative to Prize, including express warranties  provided exclusively by Prize supplier that are sent along with Prize; (c) if  selected as a Winner, to the posting of such entrant’s name on the Website and  the use by Released Parties of such name, voice, image, and/or likeness for  publicity, promotional, and advertising purposes in any and all media now or  hereafter known, throughout the world in perpetuity, without additional  compensation, notification, permission, or approval, and, upon request, to the  giving of consent, in writing, to such use; and (d) to be bound by these  Official Rules and to waive any right to claim any ambiguity or error therein  or in the Sweepstakes itself, and to be bound by all decisions of the Sponsors, which are binding and final.<strong> </strong>Failure to comply with these  conditions may result in disqualification from the Sweepstakes at Sponsors’  sole discretion.<strong></strong></p>
	<p><strong>ADDITIONAL TERMS: </strong>Sponsors  reserve the right to permanently disqualify from any promotion any person they  believe has intentionally violated these Official Rules. Any attempt to  deliberately damage the Sweepstakes or the operation thereof is unlawful and  subject to legal action by Sponsors, who may seek damages to the fullest extent  permitted by law. The failure of Sponsors to comply with any provision of these  Official Rules due to an act of God, hurricane, war, fire, riot, earthquake,  terrorism, act of public enemies, actions of governmental authorities outside  of the control of Sponsors (excepting compliance with applicable codes and  regulations), or other “force majeure” event will not be considered a breach of  these Official Rules. Released Parties assume no responsibility for any injury  or damage to entrants’ or to any other person’s computer relating to or  resulting from entering or downloading materials or software in connection with  the Sweepstakes. Released Parties are not responsible for telecommunications,  network, electronic, technical, or computer failures of any kind; for  inaccurate transcription of Entry information; for errors in any promotional or  marketing materials or in these Official Rules; for any human or electronic  error; or for Entries that are stolen, misdirected, garbled, delayed, lost,  late, damaged, or returned. Sponsors reserve the right to cancel, modify, or  suspend the Sweepstakes or any element thereof (including, without limitation,  these Official Rules) without notice in any manner and for any reason  (including, without limitation, in the event of any unanticipated occurrence  that is not fully addressed in these Official Rules). In the event of  cancellation, modification, or suspension, Sponsors reserve the right to select  Winner in a random drawing from among all eligible, non-suspect Entries  received prior to the time of the event warranting such cancellation,  modification, or suspension. Notice of such cancellation, modification, or  suspension will be posted on the Website. Sponsors may prohibit any entrant or  potential entrant from participating in the Sweepstakes, if such entrant or  potential entrant shows a disregard for these Official Rules; acts with an  intent to annoy, abuse, threaten, or harass any other entrant, Sponsors, or  Sponsors’ agents or representatives; or behaves in any other disruptive manner  (as determined by Sponsors in their sole discretion). Sponsors<strong> </strong>reserve  the right to modify these rules for clarification purposes without materially  affecting the terms and conditions of the Sweepstakes.</p>
	<p><strong>DISPUTES</strong>: <strong>The Sweepstakes is governed by, and  will be construed in accordance with, the laws of the State of New York, and  the forum and venue for any dispute shall be in New York, New York. If THE controversy or claim is not otherwise  resolved through direct discussions or mediation, it shall THEN be resolved by  FINAL AND binding arbitration administered by JUDICIAL ARBITRATION AND  MEDIATION SERVICES, INC., in accordance with its Streamlined Arbitration Rules  and Procedures or subsequent versions thereof (“JAMS Rules”). The JAMS Rules  for selection of an arbitrator shall be followed, except that the arbitrator  shall be experienced and licensed to practice law in new york. All proceedings  brought pursuant to this paragraph will be conducted in the County of new york.  THE REMEDY FOR ANY CLAIM SHALL BE LIMITED TO ACTUAL DAMAGES, AND IN NO  EVENT SHALL ANY PARTY BE ENTITLED TO RECOVER PUNITIVE, EXEMPLARY,  CONSEQUENTIAL, OR INCIDENTAL DAMAGES, INCLUDING ATTORNEYS’ FEES OR OTHER SUCH  RELATED COSTS OF BRINGING A CLAIM, OR TO RESCIND THIS AGREEMENT OR SEEK  INJUNCTIVE OR ANY OTHER EQUITABLE RELIEF. </strong></p>
	<p><strong>WINNER ANNOUNCEMENT: </strong>For the name of  the Winner, available after <?=$dayAfter ?>, visit Oxygen.com,  or send a self-addressed, stamped envelope to: The Bad Girls Club Talent Call Sweepstakes,  Oxygen Media, 75 Ninth Avenue, New York, NY 10011.<br>
	</p>
	<p>&nbsp;</p>
<p style="text-align:center; font-size:15px">&nbsp;</p></div>

</body>
</html>
