<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:og="http://ogp.me/ns#"
      xmlns:fb="http://www.facebook.com/2008/fbml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>The Bad Girls Club Talent Call Sweepstakes Official Rules | The Bad Girls Club | Oxygen</title>

<meta http-equiv="content-type" content="text/html; charset=iso-8859-1" />
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="description" content="The Bad Girls Club Talent Call Sweepstakes Official Rules <?=$start ?> — <?=$end ?> Show Title for Web Page Title:&amp;nbsp; The Bad Girls Club" />
</head>
<body>


<div style="padding:10px;">
	<p style="text-align:center"><strong>Bad  Girls Club VIP Sweepstakes</strong><br>
		<strong>Official Rules</strong><br>
		<strong>September  26, 2011—November 8, 2011</strong></p>
	<p><strong>PRELIMINARY INFORMATION:  </strong>NO PURCHASE NECESSARY. A purchase will  not improve your chances of winning. Void where prohibited. The Bad Girls Club VIP Sweepstakes  (&ldquo;Sweepstakes&rdquo;) will begin on  September 26, 2011 at 12:01 A.M. ET and end on November 8, 2011 at 1:00 A.M. ET  (&ldquo;Sweepstakes Period&rdquo;).  All times in the  Sweepstakes refer to Eastern Time (&ldquo;ET&rdquo;). Odds of winning depend upon  the number of eligible Entries (as defined below) received.  Sweepstakes is subject to all applicable  federal, state and local laws.</p>
	<p><strong>ELIGIBILITY:</strong> Open only to permanent,  legal United States (&ldquo;U.S.&rdquo;) residents who are physically residing in one (1)  of the fifty (50) U.S. or the District of Columbia (excluding Puerto Rico,  Guam, the U.S. Virgin Islands and other U.S. territories), and who are eighteen  (18) years of age or older as of the start of the Sweepstakes Period.   Officers, directors, and employees of Sweepstakes Entities (as defined  below), members of these persons&rsquo; immediate families (spouses and/or parents,  children, and siblings, and their spouses, regardless of where they reside),  and/or persons living in the same households as these persons (whether or not  related thereto) are not eligible to enter or win the Sweepstakes.  Sweepstakes Entities, as referenced herein,  shall include Oxygen Media LLC, 75 9th Ave, New York, NY  10011, NBCUniversal Media, LLC, 30 Rockefeller Plaza, New York, NY 10112,  (collectively, &ldquo;Sponsors&rdquo;), and their  respective parent, subsidiary, and affiliate companies, and their administrative, advertising, and promotion agencies, and any other entity  involved in the development, administration, promotion, or implementation of  the Sweepstakes.</p>
	<p><strong>TO ENTER:</strong> To  enter the Sweepstakes during the Sweepstakes Period, you must be a registered  member of <a href="http://www.meebo.com">www.meebo.com</a>. To become a  registered member, visit www.meebo.com and follow the provided instructions to  register for free. Please note that registration for and use of www.meebo.com  is subject to Meebo&rsquo;s Privacy Policy (https://www.meebo.com/privacy/full/).  Once registered for <a href="http://www.meebo.com/">www.meebo.com</a>, visit  the Oxygen Bad Girls Club website at <u>bad-girls-club.oxygen.com</u> (the &ldquo;Website&rdquo;), and &ldquo;check-in&rdquo; by using the Meebo toolbar (&ldquo;Check-In&rdquo;)  and then follow the provided instructions to complete and thereafter submit the  entry form, which includes your name, city, state,  e-mail address, and date of birth (&ldquo;Entry&rdquo;).  All Entries become the property of Sponsors, and will not be acknowledged.  Each  Check-In will be deemed one (1) Entry into the Sweepstakes.</p>
	<p><strong>Entries for each Weekly Drawing  must be received before end date specified in chart below. Entries for the last  Weekly Drawing (Weekly Drawing 6) must be received before November 8, 2011 at  1:00 A.M. ET to be eligible for the Sweepstakes.</strong> <strong>Limit seven (7) Entries per  person per Weekly Entry Period for a maximum of forty-two (42) entries for the  entire Sweepstakes Period. </strong>Entries  received from any person or email address beyond this limit will void all such  additional Entries. Entries generated by a script, macro, or other  automated means will be disqualified.<strong>  </strong>Entries  that are incomplete, garbled, corrupted, or unintelligible for any reason,  including, but not limited to, computer or network malfunction or congestion, are void and will not be accepted.  In case of a dispute over the identity of an entrant, the  authorized account holder of the email address used to enter will be deemed to  be the entrant. &ldquo;Authorized account holder&rdquo; is defined as the person who is  assigned to an email address by an Internet access provider, online service  provider or other organization that is responsible for assigning email  addresses for the domain associated with the submitted email address.&nbsp; Entry constitutes permission (except where prohibited by  law) to use entrant&rsquo;s name, city, state, likeness, image, and/or voice for  purposes of advertising, promotion, and publicity in any and all media now or hereafter  known, throughout the world in perpetuity, without additional compensation,  notification, permission, or approval.  <strong></strong></p>
	<p>&nbsp;</p>
	<table border="1" cellspacing="0" cellpadding="0" width="445" bordercolor="black">
		<tr>
			<td valign="top"><div><strong>Weekly    Drawing</strong></div></td>
			<td valign="top"><div><strong>Weekly    Entry Period Start Date</strong></div></td>
			<td valign="top"><div><strong>Weekly    Entry Period End Date</strong></div></td>
			<td valign="top"><div><strong>Weekly    Drawing Date</strong></div></td>
		</tr>
		<tr>
			<td valign="top"><div>1</div></td>
			<td valign="top"><div>12:01    A.M. ET on September 26, 2011</div></td>
			<td valign="top"><div>11:59    P.M. ET on October 2, 2011</div></td>
			<td valign="top"><div>On or    about October 3, 2011</div></td>
		</tr>
		<tr>
			<td valign="top"><div>2</div></td>
			<td valign="top"><div>12:01 A.M. ET on October 3, 2011</div></td>
			<td valign="top"><div>11:59 P.M. ET on October 9, 2011</div></td>
			<td valign="top"><div>On or about October 10, 2011</div></td>
		</tr>
		<tr>
			<td valign="top"><div>3</div></td>
			<td valign="top"><div>12:01 A.M. ET on October 10, 2011</div></td>
			<td valign="top"><div>11:59 P.M. ET on October 16, 2011</div></td>
			<td valign="top"><div>On or about October 17, 2011</div></td>
		</tr>
		<tr>
			<td valign="top"><div>4</div></td>
			<td valign="top"><div>12:01 A.M. ET on October 17, 2011</div></td>
			<td valign="top"><div>11:59 P.M. ET on October 23, 2011</div></td>
			<td valign="top"><div>On or about October 24, 2011</div></td>
		</tr>
		<tr>
			<td valign="top"><div>5</div></td>
			<td valign="top"><div>12:01 A.M. ET on October 24, 2011</div></td>
			<td valign="top"><div>11:59 P.M. ET on October 30, 2011</div></td>
			<td valign="top"><div>On or about October 31, 2011</div></td>
		</tr>
		<tr>
			<td valign="top"><div>6</div></td>
			<td valign="top"><div>12:01 A.M. ET on October 31, 2011</div></td>
			<td valign="top"><div>1:00 A.M. ET on November 8, 2011</div></td>
			<td valign="top"><div>On or about November 8, 2011</div></td>
		</tr>
	</table>
	<p><strong><u>PRIVACY:</u></strong> Entrants will have the opportunity to  receive information from Sponsors and selected partners by checking the  appropriate box(es). If, at any time, you no longer wish to receive materials  from Sponsors  or our partners, please go to our privacy  policy, located at <u>http://www.oxygen.com/legal/privacyPolicy.aspx</u>, or  the applicable partner&rsquo;s privacy policy and follow the procedures indicated.</p>
	<p><strong>WINNER SELECTION AND NOTIFICATION: </strong><br>
		On or about  each Weekly Drawing Date (as specified in chart above), one (1) potential  winner (&quot;Winner&quot;) will be selected in a random drawing by employees  or representatives of Sponsors from all eligible Entries received during the  Weekly Entry Period. A total of six (6) potential Winners will be selected  during the Sweepstakes Period. Sponsors will make one (1) attempt to notify  potential Winner via potential Winner's e-mail account. Noncompliance within  this time period will result in disqualification, and, at Sponsors' sole  discretion an alternate potential Winner may be selected from the remaining  eligible Entries. If potential Winner cannot be reached, is found to be  ineligible, cannot or does not comply with these Official Rules, or if prize or  prize notification is returned as undeliverable, potential Winner will be  disqualified and time permitting, at Sponsors' sole discretion, an alternate  potential Winner may be selected from the remaining eligible Entries.</p>
	<p><strong>PRIZE:</strong>  There will be six (6) prizes awarded (&ldquo;Prizes&rdquo;)  to winners  (&ldquo;Winners&rdquo;).   One Prize will be awarded to each Winner.  Each Prize will consist of the following: an  on-air mention of Winner&rsquo;s name and state in a promotion spot during a future  episode of the Bad Girls Club.  </p>
	<p>The Estimated  Retail Value (&ldquo;ERV&rdquo;) of  Prize is zero  dollars ($0).  </p>
	<p>All details of  Prize will be determined by Sponsors in their sole discretion.  Sponsors reserve the right to substitute a  similar Prize (or Prize element) of comparable or greater value. All taxes and  other expenses, costs, or fees associated with the acceptance and/or use of  Prize are the sole responsibility of Winners. Prize cannot be transferred by  Winners or redeemed for cash and is valid only for the items detailed above,  with no substitution of Prize by Winners. If Prize is unclaimed within a  reasonable time after notification from Sponsors, as determined by Sponsors in  their sole discretion, it will be  forfeited, and time permitting,  alternate Winners may be selected from the  remaining eligible Entries at Sponsors&rsquo; sole discretion.  </p>
	<p><strong>CONDITIONS: </strong>By entering the  Sweepstakes, each entrant agrees for entrant and for entrant&rsquo;s heirs,  executors, and administrators (a) to release and hold harmless Sweepstakes  Entities and their respective officers, directors, and employees (collectively,  &ldquo;Released Parties&rdquo;) from any liability, illness, injury, death, loss,  litigation, or damage that may occur, directly or indirectly, whether caused by  negligence or not, from such entrant&rsquo;s participation in the or Sweepstakes  and/or his/her acceptance, possession, use, or misuse of Prize or any portion  thereof (including any travel related thereto); (b) to indemnify Released Parties from any and all  liability resulting or arising from the Sweepstakes and to hereby  acknowledge that Released Parties have neither made nor are in any manner  responsible or liable for any warranty, representation, or guarantee, express  or implied, in fact or in law, relative to Prize, including express warranties  provided exclusively by Prize supplier that are sent along with Prize; (c) if  selected as a Winner, to the posting of such entrant&rsquo;s name on the Website and  the use by Released Parties of such name, voice, image, and/or likeness for  publicity, promotional, and advertising purposes in any and all media now or  hereafter known, throughout the world in perpetuity, without additional  compensation, notification, permission, or approval, and, upon request, to the  giving of consent, in writing, to such use; and (d) to be bound by these  Official Rules and to waive any right to claim any ambiguity or error therein  or in the Sweepstakes itself, and to be bound by all decisions of the Sponsors, which are binding and final.<strong> </strong>Failure to comply with these  conditions may result in disqualification from the Sweepstakes at Sponsors&rsquo;  sole discretion.<strong></strong></p>
<p><strong>ADDITIONAL TERMS: </strong>Sponsors  reserve the right to permanently disqualify from any promotion any person they  believe has intentionally violated these Official Rules.  Any attempt to deliberately damage the  Sweepstakes or the operation thereof is unlawful and subject to legal action by  Sponsors, who may seek damages to the fullest extent permitted by law. The  failure of Sponsors to comply with any provision of these Official Rules due to  an act of God, hurricane, war, fire, riot, earthquake, terrorism, act of public  enemies, actions of governmental authorities outside of the control of Sponsors  (excepting compliance with applicable codes and regulations), or other &ldquo;force  majeure&rdquo; event will not be considered a breach of these Official Rules.  Released Parties assume no responsibility for  any injury or damage to entrants&rsquo; or to any other person&rsquo;s computer relating to  or resulting from entering or downloading materials or software in connection  with the Sweepstakes. Released Parties are not responsible for  telecommunications, network, electronic, technical, or computer failures of any  kind; for inaccurate transcription of entry information; for errors in any  promotional or marketing materials or in these Official Rules; for any human or  electronic error; or for Entries that are stolen, misdirected, garbled,  delayed, lost, late, damaged, or returned. Sponsors reserve the right to  cancel, modify, or suspend the Sweepstakes or any element thereof (including,  without limitation, these Official Rules) without notice in any manner and for  any reason (including, without limitation, in the event of any unanticipated  occurrence that is not fully addressed in these Official Rules).  In the event of cancellation, modification,  or suspension, Sponsors reserve the right to select Winners in a random drawing  from among all eligible, non-suspect Entries received prior to the time of the  event warranting such cancellation, modification, or suspension.  Notice of such cancellation, modification, or  suspension will be posted on the Website.   Sponsors may prohibit any entrant or potential entrant from  participating in the Sweepstakes, if such entrant or potential entrant shows a  disregard for these Official Rules; acts with an intent to annoy, abuse,  threaten, or harass any other entrant, Sponsors, or Sponsors&rsquo; agents or  representatives; or behaves in any other disruptive manner (as determined by  Sponsors in their sole discretion).  Sponsor<strong> </strong>reserves  the right to modify these rules for clarification purposes without materially  affecting the terms and conditions of the Sweepstakes.	</p>
	<p><strong>DISPUTES</strong>:  <strong>The  Sweepstakes is governed by, and will be construed in accordance with, the laws  of the State of New York, and the forum and venue for any dispute shall be in New  York, New York. If THE  controversy or claim is not otherwise resolved through direct discussions or  mediation, it shall THEN be resolved by FINAL AND binding arbitration  administered by JUDICIAL ARBITRATION AND MEDIATION SERVICES, INC., in  accordance with its Streamlined Arbitration Rules and Procedures or subsequent  versions thereof (&ldquo;JAMS Rules&rdquo;).  The  JAMS Rules for selection of an arbitrator shall be followed, except that the  arbitrator shall be experienced and licensed to practice law in new york.  All proceedings brought pursuant to this  paragraph will be conducted in the County of new york.  THE REMEDY FOR ANY CLAIM SHALL BE  LIMITED TO ACTUAL DAMAGES, AND IN NO EVENT SHALL ANY PARTY BE ENTITLED TO  RECOVER PUNITIVE, EXEMPLARY, CONSEQUENTIAL, OR INCIDENTAL DAMAGES, INCLUDING  ATTORNEY&rsquo;S FEES OR OTHER SUCH RELATED COSTS OF BRINGING A CLAIM, OR TO RESCIND  THIS AGREEMENT OR SEEK INJUNCTIVE OR ANY OTHER EQUITABLE RELIEF. </strong></p>
	<p><strong>WINNER ANNOUNCEMENT: </strong>For the name of  Winners, available after November 14, 2011, visit Oxygen.com,  or send a self-addressed, stamped envelope to be received by  November 21, 2011 to: Bad Girls Club VIP  Sweepstakes, Oxygen Media, LLC,  75 9th, New York, NY 10011.</p>
	<br clear="all">
	<p style="text-align:center; font-size:15px;"><br>
</p>
	<p>&nbsp;</p>
<p style="text-align:center; font-size:15px">&nbsp;</p></div>

</body>
</html>
