      <div id="micrositeHeader">
		<img src="<?php print $pot;?>/images/BGC7_header_inseason.jpg" />
      </div>


<div id="micrositeMenu" class="<?php print $node->type;?>">
	<div id="micrositeMenuCenter">
		<div id="navHome">
		<a href="/">Bad Girls Club Home</a>
		</div>
		<div id="navMeet">
		<a href="/meet-the-cast-bgc">Bad Girls Club Bios</a>
		</div>		
		<div id="navPhotos">
		<a href="/bgc-photo-gallery-redirect-page">Bad Girls Club Photo Gallery</a>
		</div>
		<div id="navVideos">
		<a href="http://video.oxygen.com/shows/bad_girls_club_-_season_7">Bad Girls Club Videos</a> 
		<!-- <div class="navPlaceholder"> </div> -->
		</div>
		<div id="navBlogs">
		<a href="/blogs/bgc">Bad Girls Club Blogs</a>
		</div>
		<div id="navOxy">
		<a href="http://www.oxygenlive.com/event.php?show=BadGirlsClub&coast=EC">Bad Girls Club on OxygenLive.com</a>
		</div>
		<div id="navFanFavorite">
		<a href="http://bad-girls-club.oxygen.com/bad-girl-favorite">Bad Girls Club Fan Favorite</a>
		</div>
		<div id="navAbout">
		<a href="/about-the-bad-girls-club">About the Bad Girls Club</a>
		</div>
		<div id="navBoards">
		<!-- <a href="http://forums.oxygen.com/index.php?showforum=3">Chat On The Bad Girls Club Message Boards</a> -->
		<div class="navPlaceholder"> </div>
		</div>
		<div id="navShop">
		<a href="http://www.shopoholic.com/eSource/PK/ecom/eSource/default/default.aspx?store=OXYv3">Bad Girls Club Shop</a>
		</div>
	</div>
</div>
