<?php
/*
 * Generated configuration file
 * Generated by: phpMyAdmin 3.1.4 setup script by Piotr Przybylski <piotrprz@gmail.com>
 * Date: Sun, 17 May 2009 14:29:26 -0400
 */

/* Servers configuration */
$i = 0;

/* Server: oxygen-db2 [1] */
$i++;
$cfg['Servers'][$i]['verbose'] = 'oxygen-db2';
$cfg['Servers'][$i]['host'] = '10.64.80.136';
$cfg['Servers'][$i]['port'] = '';
$cfg['Servers'][$i]['socket'] = '';
$cfg['Servers'][$i]['connect_type'] = 'tcp';
$cfg['Servers'][$i]['extension'] = 'mysqli';
$cfg['Servers'][$i]['auth_type'] = 'cookie';
$cfg['Servers'][$i]['user'] = 'root';
$cfg['Servers'][$i]['password'] = 'DyP$Y6';

/* Server: oxygen-db1 [2] */
$i++;
$cfg['Servers'][$i]['verbose'] = 'oxygen-db1.1';
$cfg['Servers'][$i]['host'] = '10.64.80.135';
$cfg['Servers'][$i]['port'] = '';
$cfg['Servers'][$i]['socket'] = '';
$cfg['Servers'][$i]['connect_type'] = 'tcp';
$cfg['Servers'][$i]['extension'] = 'mysqli';
$cfg['Servers'][$i]['auth_type'] = 'cookie';
$cfg['Servers'][$i]['user'] = 'root';
$cfg['Servers'][$i]['password'] = 'DyP$Y6';

/* Server: oxygen-dbdev167 [3] */
$i++;
$cfg['Servers'][$i]['verbose'] = 'oxygen-dbdev167';
$cfg['Servers'][$i]['host'] = '10.64.80.167';
$cfg['Servers'][$i]['port'] = '';
$cfg['Servers'][$i]['socket'] = '';
$cfg['Servers'][$i]['connect_type'] = 'tcp';
$cfg['Servers'][$i]['extension'] = 'mysqli';
$cfg['Servers'][$i]['auth_type'] = 'cookie';
$cfg['Servers'][$i]['user'] = 'root';
$cfg['Servers'][$i]['password'] = 'DyP$Y6';

/* End of servers configuration */

$cfg['blowfish_secret'] = '4a1056a3a41875.11440617';
$cfg['DefaultLang'] = 'en-utf-8';
$cfg['ServerDefault'] = 1;
$cfg['UploadDir'] = '';
$cfg['SaveDir'] = '';
?>
