      <div id="micrositeHeader">
		<img src="<?php print $pot;?>/images/AAA_header_No_Tune-In.jpg" />
      </div>



      <div id="micrositeMenu" class="<?php print $node->type;?>">
		<div id="micrositeMenuCenter">
		<div id="navHome">
		<a href="/">All About Aubrey Home</a>
		</div>
		<div id="navMeet">
		<a href="http://all-about-aubrey.oxygen.com/meet-the-cast-aaa">All About Aubrey Bios</a>
		</div>		
		<div id="navPhotos">
		<a href="/aaa-photo-gallery-redirect-page">All About Aubrey Photo Gallery</a>
		</div>
		<div id="navVideos">
		<a href="http://video.oxygen.com/shows/all_about_aubrey">All About Aubrey Videos</a>
		</div>
		<div id="navBlogs">
		<a href="http://all-about-aubrey.oxygen.com/blogs/aaa">All About Aubrey Blogs</a>
		</div>
		<div id="navBoards">
		<a href="http://forums.oxygen.com/index.php?showforum=32">Chat On The All About Aubrey Message Boards</a>
		</div>
		<div id="navOxy">
		<a href="http://www.oxygenlive.com#hp_AubreyCESPanel" target="_blank">All About Aubrey on OxygenLive.com</a>
		</div>
		<div id="navAbout">
		<a href="/about-aaa">About The All About Aubrey Show</a>
		</div>
		<div id="navShop">
		<a href="http://www.shopoholic.com" target="_blank">All About Aubrey Shop</a>
		</div>

		</div>
	</div>


