      <div id="micrositeHeader">
		<img src="<?php print $pot;?>/images/HB2_header_showseason.jpg" />
      </div>

      <div id="micrositeMenu" class="<?php print $node->type;?>">
		<div id="micrositeMenuCenter">

		<div id="navHome">
		<a href="/">Hair Battle Spectacular Home</a>
		</div>
		<div id="navMeet">
		<a href="/meet-the-cast-hbs">Hair Battle Spectacular Bios</a>
		</div>		
		<div id="navPhotos">
		<a href="/hbs-gallery-redirect-page">Hair Battle Spectacular Photo Gallery</a>
		</div>
		<div id="navVideos">
		<a href="http://video.oxygen.com/shows/hair_battle_spectacular_-_season_2">Hair Battle Spectacular Videos</a>
		<!-- <div class="navPlaceholder"> </div> -->
		</div>
		<div id="navBlogs">
		<a href="/blogs/hbs">Hair Battle Spectacular Blogs</a>
		</div>
		<div id="navBoards">
		<a href="http://forums.oxygen.com/index.php?showforum=26">Chat On The Hair Battle Spectacular Message Boards</a>
		</div>
		<div id="navOxy">
		<a href="http://www.oxygenlive.com/event.php?show=HairBattleSpectacular&coast=EC">Hair Battle Spectacular on OxygenLive</a> 
		</div>
		<div id="navAbout">
		<a href="/about-hair-battle-spectacular">About The Hair Battle Spectacular</a>
		</div>
		<div id="navShop">
		<a href="http://www.shopoholic.com/eSource/PK/ecom/eSource/items/items-2-S0-lV1Oxygen-lV2OXY.aspx?store=OXYv3">Hair Battle Spectacular Shop</a>
		</div>
		<div id="navDo-Over">
		<a href="http://hair-battle-spectacular.oxygen.com/glam-slam">Hair Battle Spectacular Glam Slam Do Over</a>
		</div>		



		</div>
	</div>