      <div id="micrositeHeader">
		<img src="<?php print $pot;?>/images/DYAO_no_tunein.jpg" />
      </div>



      <div id="micrositeMenu" class="<?php print $node->type;?>">
		<div id="micrositeMenuCenter">
		<div id="navHome">
		<a href="/">Dance Your A** Off Home</a>
		</div>
		<div id="navMeet">
		<a href="/meet-the-cast-dyao">Dance Your A** Off Bios</a>
		</div>		
		<div id="navPhotos">
		<a href="/dyao-gallery-redirect">Dance Your A** Off Photo Gallery</a>
		</div>
		<div id="navVideos">
		<a href="http://video.oxygen.com/shows/dyao_season_2">Dance Your A** Off Videos</a>
		</div>
		<div id="navRecaps">
		<a href="http://video.oxygen.com/shows/dyao_season_2#////shows/dyao_season_2/recaps_2/">Dance Your A** Off Recaps</a>
		</div>
		<div id="navBlogs">
		<a href="/blogs/dyao/">Dance Your A** Off Blogs</a>
		</div>
		<div id="navExtras">
		<a href="/dance-your-a-off-extras">Dance Your A** Off Extras</a>
		</div>
		<div id="navTour">
		<a href="/dyao-tour">Dance Your A** Off Tour</a>
		</div>
		<div id="navBoards">
		<a href="http://forums.oxygen.com/index.php?showforum=19">Chat On The Dance Your A** Off Message Boards</a>
		</div>
		<div id="navAbout">
		<a href="/about-dyao">About The Dance Your A** Off Show</a>
		</div>
		<div id="navShop">
		<a href="http://www.shopoholic.com/eSource/PK/ecom/eSource/items/items-2-S0-lV1DYAO-lV2OXY.aspx?store=OXYv3">Dance Your A** Off Shop</a>
		</div>
		</div>
	</div>